/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const Timestamp = IDL.Int;
export const DeliveryLog = IDL.Record({
  'id' : Id,
  'eventId' : Id,
  'deliveredAt' : Timestamp,
  'subscriberId' : Id,
  'subscriberName' : IDL.Text,
  'deliveryStatus' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : Id,
  'publisherName' : IDL.Text,
  'timestamp' : Timestamp,
  'payload' : IDL.Text,
  'eventType' : IDL.Text,
});
export const Subscriber = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'subscribedEventType' : IDL.Text,
});

export const idlService = IDL.Service({
  'getDeliveryLogs' : IDL.Func([], [IDL.Vec(DeliveryLog)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'publishEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Event, IDL.Vec(DeliveryLog)],
      [],
    ),
  'subscribe' : IDL.Func([IDL.Text, IDL.Text], [Subscriber], []),
  'unsubscribe' : IDL.Func([Id], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const Timestamp = IDL.Int;
  const DeliveryLog = IDL.Record({
    'id' : Id,
    'eventId' : Id,
    'deliveredAt' : Timestamp,
    'subscriberId' : Id,
    'subscriberName' : IDL.Text,
    'deliveryStatus' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : Id,
    'publisherName' : IDL.Text,
    'timestamp' : Timestamp,
    'payload' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const Subscriber = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'subscribedEventType' : IDL.Text,
  });
  
  return IDL.Service({
    'getDeliveryLogs' : IDL.Func([], [IDL.Vec(DeliveryLog)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'publishEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Event, IDL.Vec(DeliveryLog)],
        [],
      ),
    'subscribe' : IDL.Func([IDL.Text, IDL.Text], [Subscriber], []),
    'unsubscribe' : IDL.Func([Id], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };