/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryLog {
  'id' : Id,
  'eventId' : Id,
  'deliveredAt' : Timestamp,
  'subscriberId' : Id,
  'subscriberName' : string,
  'deliveryStatus' : string,
}
export interface Event {
  'id' : Id,
  'publisherName' : string,
  'timestamp' : Timestamp,
  'payload' : string,
  'eventType' : string,
}
export type Id = bigint;
export interface Subscriber {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'subscribedEventType' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getDeliveryLogs' : ActorMethod<[], Array<DeliveryLog>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'publishEvent' : ActorMethod<
    [string, string, string],
    [Event, Array<DeliveryLog>]
  >,
  'subscribe' : ActorMethod<[string, string], Subscriber>,
  'unsubscribe' : ActorMethod<[Id], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];